added main script, edited fail messages and req1d invalid regex

diff --git a/req1e b/req1e
--- a/req1e
+++ b/req1e
@@ -6,13 +6,13 @@
 
 DATETIME=$(date "+%d-%m-%y %r")
 SUBJFILE='/etc/passwd'
-KEY='user:pass:uid:gid:gesoc:home_dir:command/shell'
+FORMAT='user:pass:uid:gid:gesoc:home_dir:command/shell'
 REQ='1E'
-STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
+STDOUTLOGFILE=$1
 echo "" >> "$STDOUTLOGFILE"
-echo "#################### $REQ. $(date "+%d-%m-%y %r") #########################" >> "$STDOUTLOGFILE"
+echo "#################### $REQ. Ensure system accounts are non-login  #########################" >> "$STDOUTLOGFILE"
 echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
-echo "Key: $KEY" >> "$STDOUTLOGFILE"
+echo "Format: $FORMAT" >> "$STDOUTLOGFILE"
 
 #############################
 # 1: Subject file not found #
@@ -31,4 +31,17 @@ fi
 # CMDOUT=$(grep -P "^\s*.+:x*:((\d{1,3}:\d{1,3})|(65534:65534)):.*:.*:(?!(/usr/sbin/nologin|/sbin/nologin|/bin/false))" $SUBJFILE)
 # echo "$CMDOUT"
 CMDOUT=$(awk -F: '($1!~/^(root|halt|sync|shutdown|nfsnobody)$/ && ($3<'"$(awk '/^\s*UID_MIN/{print $2}' /etc/login.defs)"' || $3 == 65534) && $7!~/^(\/usr)?\/sbin\/nologin$/) { print $1 }' /etc/passwd)
-echo $CMDOUT
+
+####################################
+# 2. Check if command is non-empty #
+####################################
+
+if ! [[ -z $CMDOUT ]]
+then
+	echo "Req 1E Testcase 2: FAIL: Verification non-empty" >> "$STDOUTLOGFILE"
+	exit 1
+
+else
+	echo "Req 1E: PASS" >> "$STDOUTLOGFILE"
+	exit 0
+fi
