major changes!

diff --git a/req1b b/req1b
--- a/req1b
+++ b/req1b
@@ -10,7 +10,7 @@ KEY='PermitEmptyPasswords'
 REQ='1B'
 #STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
 STDOUTLOGFILE=$1
-STARTFAIL=0
+#STARTFAIL=0
 echo "" >> "$STDOUTLOGFILE"
 echo "# $REQ. Ensure SSH PermitEmptyPasswords is disabled  #########################" >> "$STDOUTLOGFILE"
 echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
@@ -19,85 +19,86 @@ echo "Key: $KEY" >> "$STDOUTLOGFILE"
 ##############################
 # 1: Check SSH service start #
 ##############################
-systemctl restart sshd &> /dev/null
-if [ "$?" -ne 0 ]
-then
-	echo "Req $REQ Testcase 1: FAIL: SSH service cannot be started." >> "$STDOUTLOGFILE"
-	STARTFAIL=1
-fi
+#systemctl restart sshd &> /dev/null
+#if [ "$?" -ne 0 ]
+#then
+#	echo "Req $REQ Testcase 1: FAIL: SSH service cannot be started." >> "$STDOUTLOGFILE"
+#	STARTFAIL=1
+#fi
 
 #############################
-# 2: Subject File not Found #
+# 1: Subject File not Found #
 #############################
 if [ ! -f "$SUBJFILE" ]
 then
-        echo "Req $REQ Testcase 2: FAIL: Subject file not found." >> "$STDOUTLOGFILE"
+        echo "Req $REQ Testcase 1: FAIL: Subject file not found." >> "$STDOUTLOGFILE"
 	exit 1
 fi
 
 ####################
-# 3: Key not found #
+# 2: Key not found #
 ####################
 if [ $( grep -i "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
 then
-	echo "Req $REQ Testcase 3: FAIL: Key cannot be found." >> "$STDOUTLOGFILE"
+	echo "Req $REQ Testcase 2: FAIL: Key cannot be found." >> "$STDOUTLOGFILE"
 	exit 1
 fi
 
 ##########################
-# 4: No associated value #
+# 3: No associated value #
 ##########################
-CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -iE "^\s*$KEY\s*(#\s*\S*)*$" | wc -l)
+CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -iE "^\s*$KEY\s*(#.*)*$" | wc -l)
 if [ "$CMDOUT" -ne 0 ]
 then
-	echo "Req $REQ Testcase 4: FAIL: No value." >> "$STDOUTLOGFILE"
+	echo "Req $REQ Testcase 3: FAIL: No value." >> "$STDOUTLOGFILE"
 	exit 1
 fi
 
 ######################
-# 5. Multiple values #
+# 4. Multiple values #
 ######################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+\S+\s+(?!#).+" | wc -l)
+# CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+\S+\s+(?!#).+" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+\S+\s+(?!\s*#).*'" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
-        echo "Req $REQ Testcase 5: FAIL: Multiple values." >> "$STDOUTLOGFILE"
+        echo "Req $REQ Testcase 4: FAIL: Multiple values." >> "$STDOUTLOGFILE"
         exit 1
 fi
 
 ####################
-# 6. Invalid value #
+# 5. Invalid value #
 ####################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!yes|no)\s*)(#\s*\S*)*" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!(\s*yes|\s*no)\s*)(#.*)*" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
-	echo "Req $REQ Testcase 6: FAIL: Invalid value." >> "$STDOUTLOGFILE"
+	echo "Req $REQ Testcase 5: FAIL: Invalid value." >> "$STDOUTLOGFILE"
 	exit 1
 fi
 
 ##########################
-# 7. Non-Compliant value #
+# 6. Non-Compliant value #
 ##########################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!no)\s*(#\s*\S*)*" | wc -l)
-if [ "$CMDOUT" -ne 0  ]
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!\s*no)\s*(#.*)*" | wc -l)
+if [ "$CMDOUT" -ne 0 ]
 then
-        echo "Req $REQ Testcase 7: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
+        echo "Req $REQ Testcase 6: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
         exit 1
 fi
 
 ######################
-# 8. Compliant value #
+# 7. Compliant value #
 ######################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*(#\s*\S*)*" | wc -l)
-if [[ "$CMDOUT" -ne 0 && $STARTFAIL -ne 1 ]]
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*(#.*)*" | wc -l)
+if [ "$CMDOUT" -eq 1 ]
 then
         echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
         exit 0
 fi
 
-if [ "$STARTFAIL" -eq 1 ]
-then
-	exit 1
-fi
+#if [ "$STARTFAIL" -eq 1 ]
+#then
+#	exit 1
+#fi
 
 # If it comes to this line, it means value input is outside the scope of the testcases
 echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
diff --git a/req1d b/req1d
--- a/req1d
+++ b/req1d
@@ -23,36 +23,36 @@ convert(){
         SUBJLINE=$1
         local CHECKED=""
         local locCONVERT=""
+	local NOTDECI=true
         local ISNEGATIVE=$(echo "$SUBJLINE" | grep -E "^-.*" | wc -l)
         local VALID=false
         # Check and convert HEX -> DECI
-        if [ $( echo "$SUBJLINE" | grep -iE "^-*0x[1-9a-f]+$" | wc -l) -eq 1 ]
+        if [ $( echo "$SUBJLINE" | grep -iE "^-*0x[0-9a-f]+$" | wc -l) -eq 1 ]
         then
-                #CHECKED=$(echo "$SUBJLINE" | sed "s/^-*0[xX]//"| sed "y/abcdef/ABCDEF/")
-                locCONVERT=$((16#$(echo "$SUBJLINE" | sed "s/^-*0[xX]//"| sed "y/abcdef/ABCDEF/")))
-                VALID=true
+                #locCONVERT=$((16#$(echo "$SUBJLINE" | sed "s/0[xX]//"| sed "y/abcdef/ABCDEF/")))
+		locCONVERT=$(printf "%d" "0x5A")
+		VALID=true
 
         # Check and convert OCT -> DECI
         elif [ $( echo "$SUBJLINE" | grep -E "^-*0[0-7]+$" | wc -l) -eq 1 ]
         then
-                #CHECKED=$(echo "$SUBJLINE" | sed "s/^-*0//")
-                locCONVERT=$((8#$(echo "$SUBJLINE" | sed "s/^-*0//")))
+                locCONVERT=$((8#$(echo "$SUBJLINE" | sed "s/^0//")))
                 VALID=true
         # Check DECI
-        elif [ $( echo "$SUBJLINE" | grep -E "^-*([0-9]{1,})$" | wc -l) -eq 1 ]
+        elif [ $( echo "$SUBJLINE" | grep -E "^-*([0-9]+)$" | wc -l) -eq 1 ]
         then
                 locCONVERT=$SUBJLINE
                 VALID=true
+		NOTDECI=false
         fi
-
         # Check valid value.
         if [ $VALID == true ]
         then
-                if [ $ISNEGATIVE -eq 1 ]
+                if [ $ISNEGATIVE -eq 1 && $NOTDECI]
                 then
-                        echo "-$(($locCONVERT))"
+			echo "-$locCONVERT"
                 else
-                        echo "$(($locCONVERT))"
+                        echo "$locCONVERT"
                 fi
         else
                 echo "-2"
@@ -75,6 +75,16 @@ if [ $( grep "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
 then
 	echo "Req $REQ Testcase 2: FAIL: Key cannot be found." >> "$STDOUTLOGFILE"
 	exit 1
+fi
+
+#######################################
+# 5: Invalid Value (In-line comments) #
+#######################################
+CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | tail -1 | grep -iP "^\s*PASS_MAX_DAYS\s+(#.*)$" | wc -l)
+if [ "$CMDOUT" -ne 0 ]
+then
+        echo "Req $REQ Testcase 5: FAIL: Invalid value.in-line" >> "$STDOUTLOGFILE"
+        exit 1
 fi
 
 ##########################
@@ -100,11 +110,12 @@ fi
 ###############################
 # Shared values: Testcase 5-7 #
 ###############################
-CONVERTED=$(convert "$(grep -E "^\s*$KEY\s+" $SUBJFILE | tail -1 | awk '{$1=$1};{print $2}')")
+TOCONVERT=$(grep -E "^\s*$KEY\s+" $SUBJFILE | tail -1 | awk '{$1=$1};{print $2}')
+CONVERTED=$(printf "%d" $TOCONVERT)
 
-####################
-# 5. Invalid value #
-####################
+####################################
+# 5. Invalid value (Invalid range) #
+####################################
 if [[ $CONVERTED -lt -1 || $CONVERTED -gt 99999 ]]
 then
 	echo "Req $REQ Testcase 5: FAIL: Invalid value." >> "$STDOUTLOGFILE"
