major changes

diff --git a/req1d b/req1d
--- a/req1d
+++ b/req1d
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+#
 #########
 # Setup #
 #########
@@ -9,10 +9,6 @@ SUBJFILE='/etc/login.defs'
 KEY='PASS_MAX_DAYS'
 REQ='1D. Ensure password expiration is 90 days or less'
 STDOUTLOGFILE=$1
-#echo "" >> "$STDOUTLOGFILE"
-#echo "# $REQ. Ensure password expiration is 90 days or less #########################" >> "$STDOUTLOGFILE"
-#echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
-#echo "Key: $KEY" >> "$STDOUTLOGFILE"
 
 #############################
 # 1: Subject file not found #
@@ -32,21 +28,19 @@ then
 	exit 1
 fi
 
-#######################################
-# 3: Invalid entry (In-line comments) #
-#######################################
-CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | tail -1 | grep -iP "^\s*PASS_MAX_DAYS\s+.*(#.*)$" | wc -l)
-if [ "$CMDOUT" -ne 0 ]
-then
-        echo "[FAIL] $REQ, $KEY has an invalid entry, in-line comments, default to -1 days" >> "$STDOUTLOGFILE"
-        exit 1
-fi
+#CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | tail -1 | grep -iP "^\s*PASS_MAX_DAYS\s+.*(#.*)$" | wc -l)
+#if [ "$CMDOUT" -ne 0 ]
+#then
+#        echo "[FAIL] $REQ, $KEY has an invalid entry, in-line comments, default to -1 days" >> "$STDOUTLOGFILE"
+#        exit 1
+#fi
 
 ##########################
 # 4: No associated value #
 ##########################
-CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | tail -1 | grep "^\s*$KEY\s*$" | wc -l)
-if [ "$CMDOUT" -ne 0 ]
+CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | grep -P "^\s*$KEY\s*\S+$" | wc -l)
+# not even 1 non-empty value can be found
+if [ "$CMDOUT" -eq 0 ]
 then
 	echo "[FAIL] $REQ, $KEY has no value, default to -1 days" >> "$STDOUTLOGFILE"
 	exit 1
@@ -55,7 +49,7 @@ fi
 ######################
 # 5. Multiple values #
 ######################
-CMDOUT=$( grep -E "^\s*$KEY\s+" $SUBJFILE | tail -1 | grep -E "^\s*$KEY\s+(-*\S+\s+\S+\s*)" $SUBJFILE | wc -l)
+CMDOUT=$( grep -E "^\s*$KEY\s+" $SUBJFILE | grep -E "^\s*$KEY\s+(-*\S+\s+\S+\s*)" | wc -l)
 if [ "$CMDOUT" -ne 0 ]
 then
         echo "[FAIL] $REQ, $KEY has multiple values, default to -1 days" >> "$STDOUTLOGFILE"
@@ -65,29 +59,22 @@ fi
 ###############################
 # Shared values: Testcase 6-8 #
 ###############################
-TOCONVERT=$(grep -E "^\s*$KEY\s+" $SUBJFILE | tail -1 | awk '{$1=$1};{print $2}')
+# Finds LAST NON-EMPTY line.
+TOCONVERT=$(grep -E "^\s*$KEY\s+\S+" $SUBJFILE | tail -1 | awk '{$1=$1};{print $2}')
 CONVERTED=$(printf "%d" $TOCONVERT)
 
-###########################################
-# 6a. Invalid value (Unconvertable value) #
-###########################################
-if [ "$?" -ne 0 ]
+#####################
+# 6. Invalid value #
+#####################
+if [[ "$?" -ne 0 || $(grep -P "^\s*PASS_MAX_DAYS\s+.*(#.*)$" $SUBJFILE| wc -l) -gt 1 ]]
 then
-	echo "[FAIL] $REQ, $KEY has an invalid value (Unconvertable value), default to -1 days" >> "$STDOUTLOGFILE"
+	echo "[FAIL] $REQ, $KEY has an invalid value, default to -1 days" >>  "$STDOUTLOGFILE"
 	exit 1
 fi
 
-#####################################
-# 6b. Invalid value (Invalid range) #
-#####################################
 if [[ $CONVERTED -lt -1 || $CONVERTED -gt 99999 ]]
 then
-	if [ $CONVERTED -lt -1 ]
-	then
-		echo "[FAIL] $REQ, $KEY has an invalid value (Invalid range), default to -1 days" >>  "$STDOUTLOGFILE"
-	else
-		echo "[FAIL] $REQ, $KEY has an invalid value (Invalid range)" >> "$STDOUTLOGFILE"
-	fi
+	echo "[FAIL] $REQ, $KEY has an invalid value, default to -1 days" >>  "$STDOUTLOGFILE"
 	exit 1
 fi
 
