implemented req1d

diff --git a/req1d b/req1d
--- a/req1d
+++ b/req1d
@@ -1,1 +1,116 @@
 #!/bin/bash
+
+#########
+# Setup #
+#########
+
+DATETIME=$(date "+%d-%m-%y %r")
+SUBJFILE='/etc/login.defs'
+KEY='PASS_MAX_DAYS'
+REQ='1D'
+STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
+echo "" >> "$STDOUTLOGFILE"
+echo "#################### $REQ. $(date "+%d-%m-%y %r") #########################" >> "$STDOUTLOGFILE"
+echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
+echo "Key: $KEY" >> "$STDOUTLOGFILE"
+
+#####################
+# Utility Functions #
+#####################
+
+convert(){
+	local SUBJLINE=$1
+	local CHECKED=""
+	# Check and convert HEX -> DECI
+	if [ $( echo "$SUBJLINE" | grep -E -m 1 "^0x[1-9a-fA-F]+" | wc -l) -eq 1 ]
+	then
+        	CHECKED=$(echo "$SUBJLINE" | sed "s/^0x//"| sed "y/abcdef/ABCDEF/")
+		echo "$((16#$CHECKED))"
+	
+	# Check and convert OCT -> DECI
+	elif [ $( echo "$SUBJLINE" | grep -E -m 1 "^0[0-7]+" | wc -l) -eq 1 ]
+	then
+        	CHECKED=$(echo "$SUBJLINE" | sed "s/^0//")
+		echo "$((8#$CHECKED))"
+
+	# Check DECI
+	elif [ $( echo "$SUBJLINE" | grep -E -m 1 "^(-1|0|[0-9]{1,})" | wc -l) -eq 1 ]
+	then
+        	echo "$SUBJLINE"
+	
+	# Check INVALID
+	else
+        	echo "-2"
+	fi
+}
+
+#############################
+# 1: Subject file not found #
+#############################
+if [ ! -f "$SUBJFILE" ]
+then
+        echo "Req $REQ Testcase 1: Subject file not found." >> "$STDOUTLOGFILE"
+	exit 1
+fi
+
+####################
+# 2: Key not found #
+####################
+if [ $( grep "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
+then
+	echo "Req $REQ Testcase 2: Key cannot be found." >> "$STDOUTLOGFILE"
+	exit 1
+fi
+
+##########################
+# 3: No associated value #
+##########################
+CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep "^\s*$KEY\s*$" | wc -l)
+if [ "$CMDOUT" -ne 0 ]
+then
+	echo "Req $REQ Testcase 3: No value." >> "$STDOUTLOGFILE"
+	exit 1
+fi
+
+######################
+# 4. Multiple values #
+######################
+CMDOUT=$( grep -E "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -E "^\s*$KEY\s(-*[0-9]+\s-*[0-9]+\s*)+$" $SUBJFILE | wc -l)
+if [ "$CMDOUT" -ne 0 ]
+then
+        echo "Req $REQ Testcase 4: Multiple values" >> "$STDOUTLOGFILE"
+        exit 1
+fi
+
+
+###############################
+# Shared values: Testcase 5-7 #
+###############################
+CONVERTED=$(convert "$(grep -E -m 1 "^\s*$KEY\s+" $SUBJFILE | awk '{$1=$1};{print $2}')")
+
+####################
+# 5. Invalid value #
+####################
+if [[ $CONVERTED -lt -1 || $CONVERTED -gt 99999 ]]
+then
+	echo "Req $REQ Testcase 5: Invalid key." >> "$STDOUTLOGFILE"
+	exit 1
+fi
+
+##########################
+# 6. Non-Compliant value #
+##########################
+if [[ $CONVERTED -eq -1 || $CONVERTED -gt 90 ]]
+then
+        echo "Req $REQ Testcase 6: Non-compliant value." >> "$STDOUTLOGFILE"
+        exit 1
+fi
+
+######################
+# 7. Compliant value #
+######################
+if [[ $CONVERTED -ge 0 && $CONVERTED -le 90 ]]
+then
+        echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
+        exit 0
+fi
