Added handling for in-line comments

diff --git a/req1a b/req1a
--- a/req1a
+++ b/req1a
@@ -47,7 +47,7 @@ fi
 # 4: No associated value #
 ##########################
 # CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep "^\s*$KEY\s*$" | wc -l)
-CMDOUT=$( grep -i -m 1 "^\s*$KEY\s*$" $SUBJFILE | wc -l)
+CMDOUT=$( grep -iEm 1 "^\s*$KEY\s*(#\s*\S*)*$" $SUBJFILE | wc -l)
 if [ "$CMDOUT" -ne 0 ]
 then
 	echo "Req $REQ Testcase 4: FAIL: No value." >> "$STDOUTLOGFILE"
@@ -57,8 +57,8 @@ fi
 ######################
 # 5. Multiple values #
 ######################
-
-CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+.+\s+.+" | wc -l)
+# grep -iP '^\s*PermitRootLogin\s+(\S+\s+)(?!#\s*\S*).*$' /etc/ssh/sshd_config # matches PermitRootLogin 123<space>
+CMDOUT=$( grep -iP "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+\S+\s+(?!#).+" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
         echo "Req $REQ Testcase 5: FAIL: Multiple values." >> "$STDOUTLOGFILE"
@@ -69,7 +69,7 @@ fi
 # 6. Invalid value #
 ####################
 
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!yes|prohibit-password|forced-commands-only|no)\s*)" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!yes|prohibit-password|forced-commands-only|no)\s*)(#\s*\S*)*" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
 	echo "Req $REQ Testcase 6: FAIL: Invalid value." >> "$STDOUTLOGFILE"
@@ -79,8 +79,7 @@ fi
 ##########################
 # 7. Non-Compliant value #
 ##########################
-
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!no)\s*)" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!no)\s*(#\s*\S*)*" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
         echo "Req $REQ Testcase 7: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
@@ -91,7 +90,7 @@ fi
 # 8. Compliant value #
 ######################
 
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*$" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*(#\s+\S*)*" | wc -l)
 if [[ "$CMDOUT" -ne 0 && $STARTFAIL -ne 1 ]]
 then
         echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
@@ -102,3 +101,7 @@ if [ "$STARTFAIL" -eq 1 ]
 then
 	exit 1
 fi
+
+# If it comes to this line, it means value input is outside the scope of the testcases
+echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
+exit 1
diff --git a/req1b b/req1b
--- a/req1b
+++ b/req1b
@@ -36,7 +36,7 @@ then
 fi
 
 ####################
-# 2: Key not found #
+# 3: Key not found #
 ####################
 if [ $( grep -i "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
 then
@@ -45,9 +45,9 @@ then
 fi
 
 ##########################
-# 3: No associated value #
+# 4: No associated value #
 ##########################
-CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -i "^\s*$KEY\s*$" | wc -l)
+CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -iE "^\s*$KEY\s*(#\s*\S*)*$" | wc -l)
 if [ "$CMDOUT" -ne 0 ]
 then
 	echo "Req $REQ Testcase 4: FAIL: No value." >> "$STDOUTLOGFILE"
@@ -55,9 +55,9 @@ then
 fi
 
 ######################
-# 4. Multiple values #
+# 5. Multiple values #
 ######################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+.+\s+.+" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+\S+\s+(?!#).+" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
         echo "Req $REQ Testcase 5: FAIL: Multiple values." >> "$STDOUTLOGFILE"
@@ -65,9 +65,9 @@ then
 fi
 
 ####################
-# 5. Invalid value #
+# 6. Invalid value #
 ####################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!yes|no)\s*)" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!yes|no)\s*)(#\s*\S*)*" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
 	echo "Req $REQ Testcase 6: FAIL: Invalid value." >> "$STDOUTLOGFILE"
@@ -75,9 +75,9 @@ then
 fi
 
 ##########################
-# 6. Non-Compliant value #
+# 7. Non-Compliant value #
 ##########################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!no)\s*)" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!no)\s*(#\s*\S*)*" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
         echo "Req $REQ Testcase 7: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
@@ -85,9 +85,9 @@ then
 fi
 
 ######################
-# 7. Compliant value #
+# 8. Compliant value #
 ######################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*$" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*(#\s*\S*)*" | wc -l)
 if [[ "$CMDOUT" -ne 0 && $STARTFAIL -ne 1 ]]
 then
         echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
@@ -98,3 +98,7 @@ if [ "$STARTFAIL" -eq 1 ]
 then
 	exit 1
 fi
+
+# If it comes to this line, it means value input is outside the scope of the testcases
+echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
+exit 1
diff --git a/req1c b/req1c
--- a/req1c
+++ b/req1c
@@ -47,7 +47,7 @@ fi
 ##########################
 # 4: No associated value #
 ##########################
-CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -i "^\s*$KEY\s*$" | wc -l)
+CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -i "^\s*$KEY\s*(#\s*\S*)*$" | wc -l)
 if [ "$CMDOUT" -ne 0 ]
 then
 	echo "Req $REQ Testcase 4: FAIL: No value." >> "$STDOUTLOGFILE"
@@ -57,7 +57,7 @@ fi
 ######################
 # 5. Multiple values #
 ######################
-CMDOUT=$(grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 |grep -iP "^\s*Protocol\s(-*\S+\s+\S+\s*)" | wc -l)
+CMDOUT=$(grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 |grep -iP "^\s*$KEY\s+\S+\s+(?!#).+" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
         echo "Req $REQ Testcase 5: FAIL: Multiple values." >> "$STDOUTLOGFILE"
@@ -68,7 +68,7 @@ fi
 # 6. Invalid value #
 ####################
 #CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+[^12]\s*,?\s*[^12]?\s*" | wc -l)
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!(1\s*,\s*2|2\s*,\s*1|1|2)\s*$)" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!(1\s*,\s*2|2\s*,\s*1|1|2)\s*)(#\s*\S*)*" | wc -l)
 if [ "$CMDOUT" -ne 0  ]
 then
 	echo "Req $REQ Testcase 6: FAIL: Invalid value." >> "$STDOUTLOGFILE"
@@ -78,7 +78,7 @@ fi
 ##########################
 # 7. Non-Compliant value #
 ##########################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+2\s*$" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+2\s*(#\s*\S*)*$" | wc -l)
 if [ ! "$CMDOUT" -ne 0  ]
 then
         echo "Req $REQ Testcase 7: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
@@ -88,7 +88,7 @@ fi
 ######################
 # 8. Compliant value #
 ######################
-CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+2\s*$" | wc -l)
+CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+2\s*(#\s*\S*)*$" | wc -l)
 if [[ "$CMDOUT" -ne 0 && $STARTFAIL -ne 1 ]]
 then
         echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
@@ -99,3 +99,7 @@ if [ "$STARTFAIL" -eq 1 ]
 then
 	exit 1
 fi
+
+# If it comes to this line, it means value input is outside the scope of the testcases
+echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
+exit 1
diff --git a/req1d b/req1d
--- a/req1d
+++ b/req1d
@@ -97,7 +97,6 @@ then
         exit 1
 fi
 
-
 ###############################
 # Shared values: Testcase 5-7 #
 ###############################
@@ -129,3 +128,7 @@ then
         echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
         exit 0
 fi
+
+# If it comes to this line, it means value input is outside the scope of the testcases
+echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
+exit 1
